CREATE DATABASE OFICINA;
USE OFICINA;


CLIENTE 1X1 CARRO

CARRO
MARCA
CORES


TELEFONE NÃO PRECISAM SER NECESSÁRIOS

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM('M','F') NOT NULL,
	ID_CARRO INT UNIQUE
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('CEL','RES','COM') NOT NULL,
	NUMERO VARCHAR(30) NOT NULL,
	ID_CLIENTE INT 
);

CREATE TABLE MARCA(
	IDMARCA INT PRIMARY KEY AUTO_INCREMENT,
	MARCA VARCHAR(30) UNIQUE
);

CREATE TABLE CARRO(
	IDCARRO INT PRIMARY KEY AUTO_INCREMENT,
	MODELO VARCHAR(30) NOT NULL,
	PLACA VARCHAR(30) NOT NULL UNIQUE,
	ID_MARCA INT
);

CREATE TABLE COR(
	IDCOR INT PRIMARY KEY AUTO_INCREMENT,
	COR VARCHAR(30) UNIQUE
);

CREATE TABLE CARRO_COR(
	ID_CARRO INT,
	ID_COR INT,
	PRIMARY KEY(ID_CARRO,ID_COR)
);

/* CONSTRAINTS */

ALTER TABLE TELEFONE 
ADD CONSTRAINT FK_TELEFONE_CLIENTE
FOREIGN KEY(ID_CLIENTE)
REFERENCES CLIENTE(IDCLIENTE);

ALTER TABLE CLIENTE
ADD CONSTRAINT FK_CLIENTE_CARRO
FOREIGN KEY(ID_CARRO)
REFERENCES CARRO(IDCARRO);


ALTER TABLE CARRO
ADD CONSTRAINT FK_CARRO_MARCA
FOREIGN KEY(ID_MARCA)
REFERENCES MARCA(IDMARCA);


ALTER TABLE CARRO_COR
ADD CONSTRAINT FK_COR
FOREIGN KEY(ID_COR)
REFERENCES COR(IDCOR);


ALTER TABLE CARRO_COR
ADD CONSTRAINT FK_CARRO
FOREIGN KEY(ID_CARRO)
REFERENCES CARRO(IDCARRO);


-- PREENCHER COM NO MÍNIMO 10 CLIENTES

INSERT INTO MARCA VALUES (NULL, 'Fiat');
INSERT INTO MARCA VALUES (NULL, 'Volkswagen');
INSERT INTO MARCA VALUES (NULL, 'Chevrolet');
INSERT INTO MARCA VALUES (NULL, 'Hyundai');
INSERT INTO MARCA VALUES (NULL, 'Honda');

INSERT INTO CARRO VALUES(NULL, "PALIO", "EYJ2289", 1);
INSERT INTO CARRO VALUES(NULL, "GOL", "ABC1234", 2);
INSERT INTO CARRO VALUES(NULL, "CORSA", "XYZ5678", 3);
INSERT INTO CARRO VALUES(NULL, "UNO", "JKL9101", 1);
INSERT INTO CARRO VALUES(NULL, "HB20", "DEF3456", 4);
INSERT INTO CARRO VALUES(NULL, "ONIX", "MNO7890", 3);
INSERT INTO CARRO VALUES(NULL, "CIVIC", "PQR1122", 5);
INSERT INTO CARRO VALUES(NULL, "FIT", "STU3344", 5);
INSERT INTO CARRO VALUES(NULL, "FOX", "VWX5566", 2);
INSERT INTO CARRO VALUES (NULL, 'JETTA', 'XPT1234', 2);



																																			
INSERT INTO CLIENTE VALUES(NULL, "PEDRO", "M", 1);
INSERT INTO CLIENTE VALUES(NULL, "MARIA", "F", 2);
INSERT INTO CLIENTE VALUES(NULL, "JOÃO", "M", 3);
INSERT INTO CLIENTE VALUES(NULL, "ANA", "F", 4);
INSERT INTO CLIENTE VALUES(NULL, "CARLOS", "M", 5);
INSERT INTO CLIENTE VALUES(NULL, "FERNANDA", "F", 6);
INSERT INTO CLIENTE VALUES(NULL, "LUCAS", "M", 7);
INSERT INTO CLIENTE VALUES(NULL, "JULIANA", "F", 8);
INSERT INTO CLIENTE VALUES(NULL, "GABRIEL", "M", 9);
INSERT INTO CLIENTE VALUES(NULL, "ALAN", "M", 10);

INSERT INTO TELEFONE VALUES(NULL, "RES", "1124890758", 1);
INSERT INTO TELEFONE VALUES(NULL, "RES", "1123456789", 2);
INSERT INTO TELEFONE VALUES(NULL, "CEL", "11987654321", 3);
INSERT INTO TELEFONE VALUES(NULL, "RES", "1134567890", 4);
INSERT INTO TELEFONE VALUES(NULL, "CEL", "11976543210", 5);
INSERT INTO TELEFONE VALUES(NULL, "RES", "1145678901", 6);
INSERT INTO TELEFONE VALUES(NULL, "CEL", "11965432109", 7);
INSERT INTO TELEFONE VALUES(NULL, "RES", "1156789012", 8);
INSERT INTO TELEFONE VALUES(NULL, "CEL", "11954321098", 9);
INSERT INTO TELEFONE VALUES(NULL, "RES", "1167890123", 10);

INSERT INTO COR VALUES(NULL, "AZUL");
INSERT INTO COR VALUES(NULL, 'BRANCO');
INSERT INTO COR VALUES(NULL, 'PRETO');
INSERT INTO COR VALUES(NULL, 'PRATA');
INSERT INTO COR VALUES(NULL, 'CINZA');
INSERT INTO COR VALUES(NULL, 'VERMELHO');
INSERT INTO COR VALUES(NULL, 'VERDE');
INSERT INTO COR VALUES(NULL, 'AMARELO');
INSERT INTO COR VALUES(NULL, 'MARROM');

INSERT INTO CARRO_COR VALUES( 1, 8);
INSERT INTO CARRO_COR VALUES( 2, 9);
INSERT INTO CARRO_COR VALUES( 3, 7);
INSERT INTO CARRO_COR VALUES( 3, 6);
INSERT INTO CARRO_COR VALUES( 4, 6);
INSERT INTO CARRO_COR VALUES( 5, 5);
INSERT INTO CARRO_COR VALUES( 6, 3);
INSERT INTO CARRO_COR VALUES( 7, 2);
INSERT INTO CARRO_COR VALUES( 8, 1);
INSERT INTO CARRO_COR VALUES( 9, 3);
INSERT INTO CARRO_COR VALUES(10, 8);


SELECT NOME, MODELO FROM CARRO C
INNER JOIN CLIENTE CL
ON C.IDCARRO = CL.ID_CARRO;
